/***
* popup.js
* The script which runs when the pop-up is created.
* Used to query the content script and push the responce back into our pop-up.
*/


// Query the active tab for data
chrome.tabs.query({active: true, currentWindow: true}, function(tabs) {

	// If there is an active tab...
	if (tabs.length > 0) {
	
		// Send a message requesting the page
		chrome.tabs.sendMessage(tabs[0].id, {method: "getPage"}, function(response) {

			if (chrome.runtime.lastError) {
				// An error occurred, log it
				console.log("ERROR: ", chrome.runtime.lastError);
			} else {
				// We got the html content, process it here
				console.log(response);

				// Define a beer object
                function Beer(names,link) {

					// Array of names to look for
                    this.arrayNames=names;

					// Link to Beer advocate page
                    this.baLink=link;
				}

				// Our list of beers
				var top = [
					new Beer(["Heady Topper", "heady"], "links to be added!!"),
					new Beer(["Pliny The Younger"], ""),
					new Beer(["Pliny The Elder", "pliny"], ""),
					new Beer(["Bourbon County Brand Coffee Stout", "BCBCS"], ""),
					new Beer(["KBS", "Kentucky Breakfast Stout"], ""),
					new Beer(["Zombie Dust", " ZD "], ""),
					new Beer(["Bourbon Barrel Aged Vanilla Bean Dark Lord", "BBAVDL", "BBAVBDL"], ""),
					new Beer(["Trappist Westvleteren 12 (XII)", "Westvleteren 12", "westy 12"], ""),
					new Beer(["Double Sunshine IPA"], ""),
					new Beer(["Parabola"], ""),
					new Beer(["Cantillon Fou' Foune", "Fou' Foune", "Fou Foune"], ""),
					new Beer(["Bourbon County Brand Stout", "BCBS"], ""),
					new Beer(["Abner"], ""),
					new Beer(["Supplication"], ""),
					new Beer(["Proprietor"], ""),
					new Beer(["Abyss"], ""),
					new Beer(["Citra DIPA"], ""),
					new Beer(["Duck Duck Gooze", "DDG"], ""),
					new Beer(["Founders Breakfast Stout", "FBS"], ""),
					new Beer(["Hopslam"], ""),
					new Beer(["Rochefort 10"], ""),
					new Beer(["Hunahpu"], ""),
					new Beer(["Bourbon County Brand Barleywine Ale", "BCBB"], ""),
					new Beer(["Bourbon Barrel Aged Plead The 5th", "BBAPt5", "BBA Plead The 5th"], ""),
					new Beer(["Bourbon Barrel Fourth Dementia", "BB4D"], ""),
					new Beer(["§ucaba", "Abacus", "Sucaba"], ""),
					new Beer(["Black Note"], ""),
					new Beer(["Beatification"], ""),
					new Beer(["Abrasive"], ""),
					new Beer(["Black Tuesday"], ""),
					new Beer(["Lou Pepe - Kriek", "Lou Pepe Kriek"], ""),
					new Beer(["Ephraim"], ""),
					new Beer(["Double Galaxy"], ""),
					new Beer(["Barrel-Aged Abraxas", "BA Abraxas"], ""),
					new Beer(["Darkness"], ""),
					new Beer(["St. Bernardus Abt 12", "Bernardus 12", "Abt 12"], ""),
					new Beer(["Westvleteren 8", "westy 8"], ""),
					new Beer(["Everett Porter"], ""),
					new Beer(["Saint Lamvinus"], ""),
					new Beer(["Chocolate Rain"], ""),
					new Beer(["Permanent Funeral"], ""),
					new Beer(["PseudoSue"], ""),
					new Beer(["Mornin' Delight", "Mornin Delight", "Morning Delight"], ""),
					new Beer(["Consecration"], ""),
					new Beer(["Cable Car"], ""),
					new Beer(["Adam From The Wood", "Adam ftw"], ""),
					new Beer(["Cantillon Gueuze"], ""),
					new Beer(["Backyard Rye Bourbon County Brand Stout", "backyard rye", "BRBCBS"], ""),
					new Beer(["Temptation"], ""),
					new Beer(["Speedway Stout - Bourbon Barrel Aged", "BBA speedway"], ""),
					new Beer(["Kentucky Brunch Brand Stout", "KBBS"], ""),
					new Beer(["Enjoy By"], ""),
					new Beer(["Blåbær", "Blabaer"], ""),
					new Beer(["Double Citra"], ""),
					new Beer(["Bourbon Barrel Aged Dark Lord Imperial Stout", "BBADL", "BBA dark"], ""),
					new Beer(["Nelson"], ""),
					new Beer(["Utopias"], ""),
					new Beer(["Eclipse Stout - Elijah", "Eclipse Stout Elijah", "craig Eclipse", "eclipse elijah"], ""),
					new Beer(["bomb"], ""),
					new Beer(["California Brandy Barrel Aged", "brandy huna"], ""),
					new Beer(["Sculpin"], ""),
					new Beer(["Weihenstephaner Hefeweissbier"], ""),
					new Beer(["Dreadnaught"], ""),
					new Beer(["Mother Of All Storms", "moas"], ""),
					new Beer(["Sang Noir"], ""),
					new Beer(["Susan"], ""),
					new Beer(["Solitude #5", "Solitude 5"], ""),
					new Beer(["Péché Mortel", "peche mortel"], ""),
					new Beer(["Lou Pepe - Framboise", "Lou Pepe Framboise"], ""),
					new Beer(["Hoppy Birthday"], ""),
					new Beer(["Atrial Rubicite"], ""),
					new Beer(["Fonteinen Oude Geuze", "Fonteinen Oude Geuze", "3f geuze"], ""),
					new Beer(["Speedway Stout"], ""),
					new Beer(["Victory At Sea"], ""),
					new Beer(["Duet"], ""),
					new Beer(["Edward"], ""),
					new Beer(["Melange No. 3", "Melange number 3", "Melange 3", "melange #3"], ""),
					new Beer(["Exponential Hoppiness"], ""),
					new Beer(["Bad Boy"], ""),
					new Beer(["Lagunitas Sucks"], ""),
					new Beer(["Matt"], ""),
					new Beer(["Solitude #4", "Solitude 4"], ""),
					new Beer(["FIDY"], ""),
					new Beer(["Nugget Nectar"], ""),
					new Beer(["Founders Imperial Stout"], ""),
					new Beer(["Biscotti Break"], ""),
					new Beer(["Vietnamese Coffee"], ""),
					new Beer(["Grey Monday"], ""),
					new Beer(["Assassin"], ""),
					new Beer(["Very Sour Blackberry", "VSB"], ""),
					new Beer(["Imperial Russian Stout"], ""),
					new Beer(["Lunch"], ""),
					new Beer(["Wisconsin Belgian Red"], ""),
					new Beer(["Schaerbeekse"], ""),
					new Beer(["Lou Pepe - Gueuze", "Lou Pepe Gueuze"], ""),
					new Beer(["Bodhi"], ""),
					new Beer(["Kopi Luwak BBA", "BBA Kopi", "Kopi Luwak (Bourbon"], ""),
					new Beer(["Black Magick"], ""),
					new Beer(["Celebrator Doppelbock"], ""),
					new Beer(["Double Jack"], ""),
					new Beer(["Blind Pig"], ""),
					new Beer(["Pure Hoppiness"], ""),
					new Beer(["Drie Fonteinen Oude Geuze", "3f Oude Geuze"], ""),
					new Beer(["Silva Stout"], ""),
					new Beer(["Double Dose"], ""),
					new Beer(["Birth Of Tragedy"], ""),
					new Beer(["Citra"], ""),
					new Beer(["RareR D.O.S.", "RareR DOS", "RareRDOS", "RDOS"], ""),
					new Beer(["Furious"], ""),
					new Beer(["Raspberry Tart"], ""),
					new Beer(["Head Hunter"], ""),
					new Beer(["Pannepot"], ""),
					new Beer(["Barrel-Aged Blackout Stout", "BA Blackout"], ""),
					new Beer(["Kuhnhenn Raspberry Eisbock"], ""),
					new Beer(["Uncle Jacob"], ""),
					new Beer(["Great"], ""),
					new Beer(["Life Is Like", "Lil"], ""),
					new Beer(["Keene Idea"], ""),
					new Beer(["Backwoods Bastard"], ""),
					new Beer(["Unser Aventinus"], ""),
					new Beer(["Espresso Imperial Russian Stout"], ""),
					new Beer(["Zhukov"], ""),
					new Beer(["Wet"], ""),
					new Beer(["Framboise For A Cure", "FFAC"], ""),
					new Beer(["Firestone 17"], ""),
					new Beer(["Oude Tart With Sour Cherries", "Cherry oude", "oude with cherries"], ""),
					new Beer(["Hop Venom"], ""),
					new Beer(["Maple Bacon Coffee Porter", "MBCP"], ""),
					new Beer(["La Fin Du Monde"], ""),
					new Beer(["Rochefort 8"], ""),
					new Beer(["Older Viscosity"], ""),
					new Beer(["Masala Mama"], ""),
					new Beer(["Live Oak HefeWeizen"], ""),
					new Beer(["Arctic Devil"], ""),
					new Beer(["Imperial Russian Stout - Bourbon Barrel Aged"], ""),
					new Beer(["Julius"], ""),
					new Beer(["Old Rasputin"], ""),
					new Beer(["Ruination"], ""),
					new Beer(["Sanctification"], ""),
					new Beer(["Gandhi-Bot", "GandhiBot"], ""),
					new Beer(["Cuvée Des Jacob", "Cuvee Des Jacob"], ""),
					new Beer(["Serendipity"], ""),
					new Beer(["Oude Gueuze Tilquin", "Tilquin gueuze"], ""),
					new Beer(["Event Horizon"], ""),
					new Beer(["Kuhnhenn Bourbon Barrel Barley Wine", "KBBBW"], ""),
					new Beer(["Damon"], ""),
					new Beer(["Caractère", "Caractere"], ""),
					new Beer(["Apple Brandy Barrel-Aged Mexican Cake", "apple brandy mex"], ""),
					new Beer(["Chimay Grande Réserve (Blue)", "chimay blue", "blue chimay"], ""),
					new Beer(["RuinTen"], ""),
					new Beer(["Big Bad Baptist", "BBB"], ""),
					new Beer(["Cascade Apricot"], ""),
					new Beer(["Bois"], ""),
					new Beer(["Wings Of Armageddon"], ""),
					new Beer(["Cantillon Cuvée", "Cantillon Cuvee"], ""),
					new Beer(["Twilight Of The Idols"], ""),
					new Beer(["Vigneronne"], ""),
					new Beer(["Barrel Aged Sexual Chocolate", "BASC", "BA sex"], ""),
					new Beer(["Wulver"], ""),
					new Beer(["Peche 'n Brett", "peche n brett"], ""),
					new Beer(["Bourbon Abominable", "bbomb"], ""),
					new Beer(["Biscotti Break Bourbon", "bourbon biscot"], ""),
					new Beer(["Stormaktsporter"], ""),
					new Beer(["Westmalle Trappist Tripel", "Westmalle Tripel"], ""),
					new Beer(["Dark Lord"], ""),
					new Beer(["Terrapin Coffee Oatmeal"], ""),
					new Beer(["Saison-Brett", "Saison Brett", "SaisonBrett"], ""),
					new Beer(["Brunch Weasel"], ""),
					new Beer(["Myrcenary"], ""),
					new Beer(["Cantillon Iris"], ""),
					new Beer(["Rasputin XV"], ""),
					new Beer(["Bitter Monk"], ""),
					new Beer(["Abraxas"], ""),
					new Beer(["Framinghammer Baltic Porter - Bourbon Barrel Aged", "bourbon Framinghammer"], ""),
					new Beer(["Sang Royal"], ""),
					new Beer(["Pirate Bomb"], ""),
					new Beer(["Fuzzy Baby"], ""),
					new Beer(["90 Minute"], ""),
					new Beer(["Double Bastard"], ""),
					new Beer(["Alpha King"], ""),
					new Beer(["Rodenbach Grand Cru"], ""),
					new Beer(["Plead The 5th", "pt5"], ""),
					new Beer(["Barrel Aged B.O.R.I.S.", "BA Boris", "barrel aged boris"], ""),
					new Beer(["Cuvée Van De Keizer", "Cuvee Van De Keizer"], ""),
					new Beer(["Bourbon Barrel Barleywine Ale"], ""),
					new Beer(["Thumbprint Wild"], ""),
					new Beer(["Berserker"], ""),
					new Beer(["Humulus"], ""),
					new Beer(["Bottleworks XII", "Bottleworks 12"], ""),
					new Beer(["Sour In The Rye With Kumquats", "Sour In The Rye Kumquat", "kumquat sour in", "KSITR"], ""),
					new Beer(["Elevated"], ""),
					new Beer(["What Is Enlightenment"], ""),
					new Beer(["Cuvee De Castleton"], ""),
					new Beer(["Noyaux"], ""),
					new Beer(["The Pupil"], ""),
					new Beer(["Two Hearted"], ""),
					new Beer(["Edmund Fitzgerald"], ""),
					new Beer(["Oak Aged Yeti"], ""),
					new Beer(["Curieux"], ""),
					new Beer(["Fantôme Saison", "Fantome Saison"], ""),
					new Beer(["Cantillon Kriek"], ""),
					new Beer(["Deliverance"], ""),
					new Beer(["Le Terroir"], ""),
					new Beer(["White Rajah"], ""),
					new Beer(["Kiwi Rising"], ""),
					new Beer(["DRIPA"], ""),
					new Beer(["Kopi Luwak"], ""),
					new Beer(["Solitude #6", "Solitude 6"], ""),
					new Beer(["Duvel"], ""),
					new Beer(["Founders Porter"], ""),
					new Beer(["Union Jack"], ""),
					new Beer(["Choklat"], ""),
					new Beer(["Founders Harvest"], ""),
					new Beer(["Espresso Oak Aged Yeti"], ""),
					new Beer(["DirtWolf", "Dirt Wolf"], ""),
					new Beer(["Odell IPA"], ""),
					new Beer(["Hoponius Union"], ""),
					new Beer(["Pannepot Reserva"], ""),
					new Beer(["Good Gourd"], ""),
					new Beer(["Knuckle Sandwich"], ""),
					new Beer(["The Wanderer"], ""),
					new Beer(["Triple Play"], ""),
					new Beer(["Unicorn Galaxy"], ""),
					new Beer(["Black Damnation V"], ""),
					new Beer(["Jai Alai"], ""),
					new Beer(["Flower Power"], ""),
					new Beer(["Tripel Karmeliet"], ""),
					new Beer(["AleSmith IPA"], ""),
					new Beer(["La Folie"], ""),
					new Beer(["Weihenstephaner Vitus"], ""),
					new Beer(["Weihenstephaner Hefeweissbier Dunkel"], ""),
					new Beer(["Oude Tart"], ""),
					new Beer([" MO "], ""),
					new Beer(["Chillwave"], ""),
					new Beer(["Girardin Gueuze"], ""),
					new Beer(["Simtra"], ""),
					new Beer(["Cherry Adam", "CAFTW"], ""),
					new Beer(["Andechser Doppelbock Dunkel"], ""),
					new Beer(["Lindley Park"], ""),
					new Beer(["Farmer's Reserve #3", "Farmer's Reserve 3"], ""),
					new Beer(["Tartare"], ""),
					new Beer(["Czar Jack"], ""),
					new Beer(["Bligh's Barleywine Ale", "Blighs Barleywine Ale"], ""),
					new Beer(["Citra Pale Ale"], ""),
					new Beer(["Tweak"], ""),
					new Beer(["Notorious"], ""),
					new Beer(["stone IPA"], ""),
					new Beer(["Hop Rod Rye"], ""),
					new Beer(["Wookey Jack"], ""),
					new Beer(["Arctic Panzer Wolf"], ""),
				];

				// takes in a beer, checks if it is found, adds it to the table
				function findBeer(beer, i) {
					for (var j = 0; j < beer.arrayNames.length; j++) {
						if(~response.htmlContent.toLowerCase().indexOf(beer.arrayNames[j].toLowerCase())) {
													console.log("Found " + (i + 1) + ": " + beer.arrayNames[j]);
							var bl = document.getElementById('beerList');
							var beertext = document.createTextNode("Found " + (i + 1) + ": " + beer.arrayNames[j]);
							var entry = document.createElement('li');
							entry.appendChild(beertext);
							bl.appendChild(entry);
							return;
						}
					}
				}

				// Go through the list and check if it is in the webpage
				for (var i = 0; i < top.length; i++) {
					findBeer(top[i], i);
				}
			}
		});
	}
});